config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "figurines#index"

  resources :figurines do
    resources :bookings, only: [:create, :destroy]
  end
  resources :universes, except: [:show]
  resources :families, except: [:show]
  resources :specialities, except: [:show]
  resources :artists, except: [:show]
  resources :games, except: [:show]
end

app/models/figurine.rb
class Figurine < ApplicationRecord
  validates :name, presence: true
  validates :reference_picture, :painted_picture, :portrait, picture: true

  has_one_attached :reference_picture
  has_one_attached :painted_picture
  has_one_attached :portrait

  belongs_to :universe, optional: true
  belongs_to :artist, optional: true
  belongs_to :family, optional: true
  belongs_to :speciality, optional: true

  has_many :bookings, dependent: :destroy
  has_many :games, through: :bookings

  has_many :figurine_specialities, dependent: :destroy
  has_many :specialities, through: :figurine_specialities

  before_save :set_boolean_fields

  def set_boolean_fields
    self.is_painted = painted_picture.present?
    self.has_portrait = portrait.present?
  end

  def speciality_list
    specialities.map(&:name).join(", ")
  end

  def self.search(param)
    if param
      Figurine.eager_load(:universe, :family, :artist, :specialities).
      where("figurines.name LIKE :param OR
        universes.name LIKE :param OR
        families.name LIKE :param OR
        artists.name LIKE :param OR
        specialities.name LIKE :param",
        param: "%#{param}%")
    else
      Figurine.all
    end
  end
end

app/controllers/figurines_controller.rb
class FigurinesController < ApplicationController
  http_basic_authenticate_with name: ENV['APP_USERNAME'], password: ENV['APP_PASSWORD'], except: [:index, :show] if Rails.env.production?
  helper_method :sort_column, :sort_direction

  SORTABLE_FIELDS = ["figurines.name", "universes.name", "families.name", "is_painted", "artists.name", "has_portrait"]

  def index
    @filtered_figurines = Figurine.search(params[:search])
    @figurines = @filtered_figurines.eager_load(:universe, :family, :artist).order("#{sort_column} #{sort_direction}", name: :asc).paginate(params[:page])
    @total = @filtered_figurines.count
  end

  def show
    @figurine = Figurine.find(params[:id])
    @booking = Booking.new
    @bookings = @figurine.bookings
  end

  def new
    @figurine = Figurine.new
  end

  def create
    @figurine = Figurine.new(figurine_params)

    if @figurine.save
      redirect_to @figurine
    else
      render :new
    end
  end

  def edit
    @figurine = Figurine.find(params[:id])
  end

  def update
    @figurine = Figurine.find(params[:id])

    if @figurine.update(figurine_params)
      redirect_to @figurine
    else
      render :edit
    end
  end

  def destroy
    @figurine = Figurine.find(params[:id])
    @figurine.destroy

    redirect_to root_path
  end

  private
  def figurine_params
    params.require(:figurine).permit(:name, :comment, :reference_picture,
                                      :painted_picture, :portrait, :universe_id,
                                      :artist_id, :family_id, speciality_ids: [])
  end

  def sort_column
    SORTABLE_FIELDS.include?(params[:sort]) ? params[:sort] : "figurines.name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/views/figurines/_booking_modal.html.erb
<div class="modal fade" id="bookingModal" tabindex="-1" aria-labelledby="bookingModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="bookingModalLabel"><%= "Réserver #{figurine.name}" %></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form_with model: [figurine, booking] do |f| %>
          <div class="mb-3">
            <%= f.label "Partie", class: "form-label" %><br>
            <%= f.collection_select :game_id, Game.available_for_figurine(figurine), :id, :name_with_date, {}, {class: "form-select"} %>
            <% booking.errors.full_messages_for(:game_id).each do |message| %>
            <div><%= message %></div>
            <% end %>
          </div>

          <div class="mb-3">
            <%= f.label "Joueur", class: "form-label" %><br>
            <%= f.text_field :player, class: "form-control" %>
            <% booking.errors.full_messages_for(:player).each do |message| %>
              <div><%= message %></div>
            <% end %>
          </div>

          <div>
            <%= f.submit "Enregistrer", class: "btn btn-dark" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/figurines/_form.html.erb
<%= form_with model: figurine do |f| %>
  <div class="mb-3">
    <%= f.label "Nom", class: "form-label" %><br>
    <%= f.text_field :name, class: "form-control" %>
    <% figurine.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="mb-3">
    <%= f.label "Univers", class: "form-label" %><br>
    <%= f.collection_select :universe_id, Universe.all, :id, :name, {include_blank: true}, {class: "form-select"} %>
    <% figurine.errors.full_messages_for(:universe_id).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="mb-3">
    <%= f.label "Espèce", class: "form-label" %><br>
    <%= f.collection_select :family_id, Family.all, :id, :name, {include_blank: true}, {class: "form-select"} %>
    <% figurine.errors.full_messages_for(:family_id).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="mb-3">
    <%= f.label "Classes", class: "form-label" %><br>
    <div class="checkboxes-group">
      <%= f.collection_check_boxes :speciality_ids, Speciality.all, :id, :name do |speciality| %>
        <div class="form-check">
          <%= speciality.label do %>
            <%= speciality.check_box class: 'form-check-input' %>
            <%= speciality.text %>
          <% end %>
        </div>
      <% end %>
    </div>
    <% figurine.errors.full_messages_for(:speciality_ids).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="mb-3">
    <%= f.label "Commentaire", class: "form-label" %><br>
    <%= f.text_area :comment, class: "form-control" %>
    <% figurine.errors.full_messages_for(:comment).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="mb-3">
    <%= f.label "Image de référence", class: "form-label" %><br>
    <%= render "picture_name", picture: figurine.reference_picture %>
    <%= f.file_field :reference_picture, class: "form-control-file" %>
    <% figurine.errors.full_messages_for(:reference_picture).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="mb-3">
    <%= f.label "Figurine peinte", class: "form-label" %><br>
    <%= render "picture_name", picture: figurine.painted_picture %>
    <%= f.file_field :painted_picture, class: "form-control-file" %>
    <% figurine.errors.full_messages_for(:painted_picture).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="mb-3">
    <%= f.label "Artiste", class: "form-label" %><br>
    <%= f.collection_select :artist_id, Artist.all, :id, :name, {include_blank: true}, {class: "form-select"} %>
    <% figurine.errors.full_messages_for(:artist_id).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="mb-3">
    <%= f.label "Portrait", class: "form-label" %><br>
    <%= render "picture_name", picture: figurine.portrait %>
    <%= f.file_field :portrait, class: "form-control-file" %>
    <% figurine.errors.full_messages_for(:portrait).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= f.submit "Enregistrer", class: "btn btn-dark" %>
  </div>
<% end %>

app/views/figurines/_mini_picture.html.erb
<% if picture.present? %>
  <%= image_tag picture.variant(resize_to_limit: [100, 100]), class: "img-fluid" %>
<% else %>
  <p class="missing-picture"><i class='fa fa-camera'></i></p>
<% end %>

app/views/figurines/_picture.html.erb
<% if picture.present? %>
  <%= link_to rails_blob_path(picture, disposition: "attachment"), class: "download-picture", 'data-bs-toggle' => "tooltip", title: "Télécharger l'image" do %>
    <%= image_tag picture.variant(resize_to_limit: [500, 500]), class: "img-fluid" %>
  <% end %>
<% else %>
  <p class="missing-picture"><i class='fa fa-camera'></i> Image manquante</p>
<% end %>

app/views/figurines/_picture_name.html.erb
<% if picture.present? %>
  <p class="small font-italic">Fichier actuel : <%= picture.filename %></p>
<% end %>

app/views/figurines/_played_games.html.erb
<% if bookings.any? %>
  <ul>
    <% bookings.each do |booking| %>
      <li class="played-games-item">
        <%= "#{booking.game.name_with_date} - par #{booking.player}" %>
        <%= link_to figurine_booking_path(booking.figurine, booking), method: :delete, data: { confirm: "Confirmer la suppression ?" } do %>
        <i class="fa fa-times delete-link"></i>
        <% end %>
      </li>
    <% end %>
  </ul>
<% else %>
  Pas encore de partie jouée :(
<% end %>

app/views/figurines/_search_bar.html.erb
<%= form_tag figurines_path, method: :get, class: "d-flex" do %>
  <div class="hidden">
    <%= text_field_tag :direction, params[:direction] %>
    <%= text_field_tag :sort, params[:sort] %>
  </div>
  <%= text_field_tag :search, params[:search], placeholder: "Nom, univers...", class: "form-control me-2" %>
  <%= submit_tag "Chercher", class: "btn btn-outline-dark" %>
<% end %>

app/views/figurines/edit.html.erb
<h1>Modifier la figurine</h1>

<%= render "form", figurine: @figurine %>

app/views/figurines/index.html.erb
<h1>Liste des figurines (<%= @total %>)</h1>

<div class='list-actions'>
  <%= paginate @figurines %>
  <%= render "search_bar" %>
  <%= link_to "Ajouter une figurine", new_figurine_path, class: "btn btn-dark" %>
</div>

<table class="table table-striped">
  <thead>
    <tr class="figurines-header">
      <th scope="col"><%= sortable "figurines.name", display_order_arrow("Nom"), figurines_path %></th>
      <th scope="col">Référence</th>
      <th scope="col"><%= sortable "universes.name", display_order_arrow("Univers"), figurines_path %></th>
      <th scope="col"><%= sortable "families.name", display_order_arrow("Espèce"), figurines_path %></th>
      <th scope="col">Classes</th>
      <th scope="col"><%= sortable "is_painted", display_order_arrow("Peinte"), figurines_path %></th>
      <th scope="col"><%= sortable "artists.name", display_order_arrow("Artiste"), figurines_path %></th>
      <th scope="col"><%= sortable "has_portrait", display_order_arrow("Portrait"), figurines_path %></th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @figurines.each do |figurine| %>
      <tr>
        <th scope="row"><%= figurine.name %></th>
        <td class="text-center"><%= render "mini_picture", picture: figurine.reference_picture %></td>
        <td><%= figurine.universe&.name %></td>
        <td><%= figurine.family&.name %></td>
        <td>
          <ul>
            <% figurine.specialities.each do |speciality| %>
              <li><%= speciality.name %></li>
            <% end %>
          </ul>
        </td>
        <td class="text-center"><%= display_boolean(figurine.is_painted) %></td>
        <td><%= figurine.artist&.name %></td>
        <td class="text-center"><%= display_boolean(figurine.has_portrait) %></td>
        <td><%= link_to "Voir la fiche", figurine %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/figurines/new.html.erb
<h1>Nouvelle figurine</h1>

<%= render "form", figurine: @figurine %>

app/views/figurines/show.html.erb
<%= link_to "<i class='fa fa-arrow-left'></i> Revenir à la liste".html_safe, figurines_path, class: "back-link" %>

<div class="card text-dark bg-light mb-3 figurine-card">
  <div class="card-header">
    <h1 class="m-0"><%= @figurine.name %></h1>
    <p class="m-0">
      <%= link_to "Réserver pour une partie", "#",
                  data: {"bs-toggle" => "modal", "bs-target" => "#bookingModal"} %> |
      <%= link_to "Modifier", edit_figurine_path(@figurine) %> |
      <%= link_to "Supprimer", figurine_path(@figurine),
                  method: :delete,
                  data: { confirm: "Confirmer la suppression ?" } %>
    </p>
  </div>
  <div class="card-body">
    <div class="card mb-3">
      <div class="row g-0">
        <div class="col-md-6">
          <div class="card-body">
            <%= render "picture", picture: @figurine.portrait %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="card-body">
            <p class="card-text"><span class="font-weight-bold">Univers : </span><%= @figurine.universe&.name %></p>
            <p class="card-text"><span class="font-weight-bold">Espèce : </span><%= @figurine.family&.name %></p>
            <p class="card-text"><span class="font-weight-bold">Classes : </span><%= @figurine.speciality_list %></p>
            <p class="card-text"><span class="font-weight-bold">Commentaire : </span><%= @figurine.comment %></p>
            <p class="card-text"><span class="font-weight-bold">Artiste : </span><%= @figurine.artist&.name %></p>
          </div>
        </div>
      </div>
    </div>
    <div class="card mb-3">
      <div class="row g-0">
        <div class="col-md-6">
          <div class="card-body">
            <%= render "picture", picture: @figurine.reference_picture %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="card-body">
            <%= render "picture", picture: @figurine.painted_picture %>
          </div>
        </div>
      </div>
    </div>
    <div class="card mb-3">
      <div class="card-body">
        <p class="card-text font-weight-bold">Parties jouées :</p>
        <%= render "played_games", bookings: @bookings %>
      </div>
    </div>
  </div>
</div>

<%= render "booking_modal", booking: @booking, figurine: @figurine %>