config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "figurines#index"

  resources :figurines do
    resources :bookings, only: [:create, :destroy]
  end
  resources :universes, except: [:show]
  resources :families, except: [:show]
  resources :specialities, except: [:show]
  resources :artists, except: [:show]
  resources :games, except: [:show]
end

app/models/artist.rb
class Artist < ApplicationRecord
  validates :name, presence: true

  has_many :figurines
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  http_basic_authenticate_with name: ENV['APP_USERNAME'], password: ENV['APP_PASSWORD'], except: [:index] if Rails.env.production?

  def index
    @artists = Artist.order(:name).paginate(params[:page])
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)

    if @artist.save
      redirect_to artists_path
    else
      render :new
    end
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])

    if @artist.update(artist_params)
      redirect_to artists_path
    else
      render :edit
    end
  end

  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy

    redirect_to artists_path
  end

  private
  def artist_params
    params.require(:artist).permit(:name)
  end
end

app/views/artists/_form.html.erb
<%= form_with model: @artist do |f| %>
  <div class="mb-3">
    <%= f.label "Nom", class: "form-label" %><br>
    <%= f.text_field :name, class: "form-control" %>
    <% @artist.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= f.submit "Enregistrer", class: "btn btn-dark" %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Modifier l'artiste</h1>

<%= render "form", artist: @artist %>

app/views/artists/index.html.erb
<h1>Liste des artistes</h1>

<div class='list-actions'>
  <%= paginate @artists %>
  <%= link_to "Ajouter un artiste", new_artist_path, class: "btn btn-dark" %>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Nom</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <th scope="row"><%= artist.name %></th>
        <td><%= link_to "Modifier", edit_artist_path(artist) %> |
            <%= link_to "Supprimer", artist_path(artist), method: :delete, data: { confirm: "Confirmer la suppression ?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/artists/new.html.erb
<h1>Nouvel artiste</h1>

<%= render "form", artist: @artist %>