config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "figurines#index"

  resources :figurines do
    resources :bookings, only: [:create, :destroy]
  end
  resources :universes, except: [:show]
  resources :families, except: [:show]
  resources :specialities, except: [:show]
  resources :artists, except: [:show]
  resources :games, except: [:show]
end

app/models/family.rb
class Family < ApplicationRecord
  validates :name, presence: true

  has_many :figurines
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  http_basic_authenticate_with name: ENV['APP_USERNAME'], password: ENV['APP_PASSWORD'], except: [:index] if Rails.env.production?

  def index
    @families = Family.order(:name).paginate(params[:page])
  end

  def new
    @family = Family.new
  end

  def create
    @family = Family.new(family_params)

    if @family.save
      redirect_to families_path
    else
      render :new
    end
  end

  def edit
    @family = Family.find(params[:id])
  end

  def update
    @family = Family.find(params[:id])

    if @family.update(family_params)
      redirect_to families_path
    else
      render :edit
    end
  end

  def destroy
    @family = Family.find(params[:id])
    @family.destroy

    redirect_to families_path
  end

  private
  def family_params
    params.require(:family).permit(:name)
  end
end

app/views/families/_form.html.erb
<%= form_with model: @family do |f| %>
  <div class="mb-3">
    <%= f.label "Nom", class: "form-label" %><br>
    <%= f.text_field :name, class: "form-control" %>
    <% @family.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= f.submit "Enregistrer", class: "btn btn-dark" %>
  </div>
<% end %>

app/views/families/edit.html.erb
<h1>Modifier l'espèce</h1>

<%= render "form", family: @family %>

app/views/families/index.html.erb
<h1>Liste des espèces</h1>

<div class='list-actions'>
  <%= paginate @families %>
  <%= link_to "Ajouter une espèce", new_family_path, class: "btn btn-dark" %>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Nom</th>
      <th scope="col">Nb de figurines</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @families.each do |family| %>
      <tr>
        <th scope="row"><%= family.name %></th>
        <td><%= family.figurines.count %></td>
        <td><%= link_to "Modifier", edit_family_path(family) %> |
            <%= link_to "Supprimer", family_path(family), method: :delete, data: { confirm: "Confirmer la suppression ?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/families/new.html.erb
<h1>Nouvelle espèce</h1>

<%= render "form", family: @family %>