config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "figurines#index"

  resources :figurines do
    resources :bookings, only: [:create, :destroy]
  end
  resources :universes, except: [:show]
  resources :families, except: [:show]
  resources :specialities, except: [:show]
  resources :artists, except: [:show]
  resources :games, except: [:show]
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/"><%= image_pack_tag "skull.png" %></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Figurines", figurines_path, class: "nav-link #{active_class(figurines_path)}" %>
        </li>
        <li class="nav-item">
          <%= link_to "Univers", universes_path, class: "nav-link #{active_class(universes_path)}" %>
        </li>
        <li class="nav-item">
          <%= link_to "Espèces", families_path, class: "nav-link #{active_class(families_path)}" %>
        </li>
        <li class="nav-item">
          <%= link_to "Classes", specialities_path, class: "nav-link #{active_class(specialities_path)}" %>
        </li>
        <li class="nav-item">
          <%= link_to "Artistes", artists_path, class: "nav-link #{active_class(artists_path)}" %>
        </li>
        <li class="nav-item">
          <%= link_to "Parties", games_path, class: "nav-link #{active_class(games_path)}" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Robin's Collection</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_pack_tag 'skull.png' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>